/// Flutter icons TestIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  TestIcons
///      fonts:
///       - asset: fonts/TestIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class TestIcons {
  TestIcons._();

  static const _kFontFam = 'TestIcons';
  static const String? _kFontPkg = null;

  static const IconData queue_last = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData queue_first = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
